### PR TITLE
Agent Framework Adapter for Cerebrum

### PR DESCRIPTION
**Pull request by 2020-qqtcg**
Migrate agent framework adapter to Cerebrum

### CODE REVIEW

**Review by dongyuanjushi — COMMENTED** [review]
Could you upload the screenshots of the execution results of using the demo agents built by autogen, open-interpreter and metagpt?

**Comment by 2020-qqtcg** [comment]
> Could you upload the screenshots of the execution results of using the demo agents built by autogen, open-interpreter and metagpt?

Alright, should I put it in the document or write it in the PR?

**Comment by evison** [comment]
> > Could you upload the screenshots of the execution results of using the demo agents built by autogen, open-interpreter and metagpt?
> 
> Alright, should I put it in the document or write it in the PR?

Please write it here in the PR. Besides, a new pull was merged into the main branch just now to fix the tool loading issue. Could you test if your pull still works under the new code? Thanks.

**Comment by 2020-qqtcg** [comment]
> > > Could you upload the screenshots of the execution results of using the demo agents built by autogen, open-interpreter and metagpt?
> > 
> > 
> > Alright, should I put it in the document or write it in the PR?
> 
> Please write it here in the PR. Besides, a new pull was merged into the main branch just now to fix the tool loading issue. Could you test if your pull still works under the new code? Thanks.

Got it.

**Comment by 2020-qqtcg** [comment]
## AutoGen

```shell
$ python example/aios_demo.py --llm_name gpt-4o-mini --llm_backend openai --aios_kernel_url http://127.0.0.1:8000 --agent autogen/autogen_demo_agent --task "How to study deep learning?"

🔧 Starting AIOS Demo with configuration:
  LLM: gpt-4o-mini (openai)
  Root Directory: root
  Memory Limit: 524288000 bytes
  Max Workers: 32
  Timeout: 300 seconds
  Agent: autogen/autogen_demo_agent
  Task: How to study deep learning?
--------------------------------------------------
✅ Client initialized successfully
Status: {'llm': 'active', 'storage': 'active', 'memory': 'active', 'tool': 'active', 'scheduler': 'active', 'factory': 'active'}
🚀 Executing agent: autogen_demo_agent
📋 Task: How to study deep learning?
✅ Agent execution completed

📊 Final Result:
{'agent_name': 'autogen/autogen_demo_agent', 'result': [{'content': 'How to study deep learning?', 'role': 'assistant', 'name': 'joe'}, {'content': 'Hi Joe! It\'s great that you\'re interested in studying deep learning. Here’s a structured approach to help you get started:\n\n1. **Understand the Basics of Machine Learning**:\n   - Before diving into deep learning, make sure you have a grasp of basic machine learning concepts. You can explore resources like "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow" by Aurélien Géron.\n\n2. **Learn Python**:\n   - Deep learning frameworks like TensorFlow and PyTorch are primarily based on Python. If you\'re not comfortable with Python yet, consider taking some online courses or working through Codecademy\'s Python track.\n\n3. **Study Linear Algebra and Calculus**:\n   - Deep learning relies heavily on mathematical concepts such as matrices, vectors, derivatives, and gradients. Khan Academy or 3Blue1Brown are excellent resources for brushing up on these topics.\n\n4. **Explore Deep Learning Concepts**:\n   - Start with the foundational concepts, including neural networks, activation functions, forward propagation, backpropagation, and gradient descent. Websites like Coursera and edX offer courses specifically on deep learning that you can follow.\n\n5. **Hands-On Practice**:\n   - Implement simple neural networks using frameworks like Keras or PyTorch. Start with basic datasets like MNIST (handwritten digits) and work your way up to more complex datasets.\n   - Kaggle is a great platform to find datasets and participate in competitions. It’s also a good community to learn from.\n\n6. **Study Advanced Topics**:\n   - Once you\'re comfortable with the basics, explore advanced topics such as convolutional neural networks (CNNs), recurrent neural networks (RNNs), and generative adversarial networks (GANs).\n\n7. **Read Research Papers**:\n   - Deep learning is a rapidly evolving field, so staying updated with the latest research is important. Websites like arXiv.org host many relevant papers.\n\n8. **Join a Community**:\n   - Join online forums or local meetups to discuss concepts and challenges with others. Communities like Reddit, LinkedIn groups, or Discord servers can be valuable resources.\n\n9. **Build Projects**:\n   - Building projects is one of the best ways to reinforce what you’ve learned. Try creating a project that interests you, whether it’s an image classifier, a chatbot, or a game AI.\n\n10. **Stay Curious and Keep Learning**:\n    - Deep learning is a vast field, and there\'s always something new to learn. Keep experimenting with different models and techniques.\n\nFeel free to ask if you have specific questions or need recommendations on resources to get started!', 'role': 'user', 'name': 'cathy'}, {'content': 'Hi Cathy! Thank you for the suggestions; they provide a clear and structured path for studying deep learning. I appreciate the emphasis on both foundational knowledge and practical experience. I have a couple of specific questions:\n\n1. Do you have any recommendations for beginner-friendly online courses specifically for deep learning?\n2. Are there any specific projects you think would be ideal for someone just starting out with deep learning?', 'role': 'assistant', 'name': 'joe'}, {'content': "Hi Joe! I'm glad you found the suggestions helpful! Here are some recommendations for your specific questions:\n\n### 1. Beginner-Friendly Online Courses for Deep Learning:\n\n- **Coursera – Deep Learning Specialization by Andrew Ng**:\n  This is one of the most popular courses on deep learning. It covers the fundamentals, including neural networks, CNNs, and RNNs, and it's very beginner-friendly.\n\n- **edX – Introduction to Artificial Intelligence (AI) by IBM**:\n  This course provides a good foundation in AI and machine learning before diving into deep learning. \n\n- **Udacity – Intro to TensorFlow for Deep Learning**:\n  This course focuses on using TensorFlow for deep learning and includes hands-on projects, which is great for practical experience.\n\n- **Fast.ai – Practical Deep Learning for Coders**:\n  This is a hands-on course that emphasizes getting started with deep learning quickly with practical coding exercises. It's great if you have some programming experience.\n\n- **Kaggle – Intro to Deep Learning**:\n  Kaggle’s courses are free and provide practical examples, making it a great place to start learning.\n\n### 2. Specific Projects for Beginners:\n\nHere are a few projects that are ideal for someone just starting out with deep learning:\n\n- **Image Classification with MNIST**:\n  Create a neural network to recognize handwritten digits. This classic dataset is simple and a great starting point for beginners.\n\n- **Sign Language Recognition**:\n  Build a model that can recognize hand gestures or sign language using a simple CNN. The dataset can be found on platforms like Kaggle.\n\n- **Sentiment Analysis**:\n  Use a pre-labeled dataset (like movie reviews) to create a model that can analyze text and classify it as positive, negative, or neutral.\n\n- **Face Detection and Recognition**:\n  Build a simple project that uses pretrained models (like Haar cascades or OpenCV) to detect faces in images or videos.\n\n- **Image-to-Image Translation with GANs**:\n  If you're feeling adventurous, you could try implementing a basic GAN using a dataset (like cat vs. dog images) to generate new images based on input.\n\n- **Text Generation**:\n  Use an RNN or LSTM to generate text based on a given corpus of text data (like song lyrics or a book).\n\nThese projects will not only reinforce your understanding of deep learning concepts but also give you a portfolio to showcase your skills. If you have any more questions or need further guidance on any of these topics, feel free to ask!", 'role': 'user', 'name': 'cathy'}, {'content': 'Thank you, Cathy! Those course recommendations look fantastic, and the project ideas sound engaging and doable. I’m especially interested in the sentiment analysis and image classification projects to start with. \n\nI’ll go through these resources and start planning my learning journey. If I have more questions along the way or need clarification on any concepts, would it be okay to reach out again for help?', 'role': 'assistant', 'name': 'joe'}, {'content': "Absolutely, Joe! I'm here to help you through your learning journey. Feel free to reach out anytime you have questions or need clarification on concepts—whether it's about the courses, projects, or anything else related to deep learning. \n\nI'm excited to hear about your progress, and I can’t wait to see what you create with the sentiment analysis and image classification projects! Good luck, and remember to enjoy the learning process!", 'role': 'user', 'name': 'cathy'}], 'rounds': 1}
```



## MetaGPT

```shell
$ export METAGPT_PROJECT_ROOT=/root/Cerebrum 
$ python example/aios_demo.py --llm_name gpt-4o-mini --llm_backend openai --aios_kernel_url http://127.0.0.1:8000 --agent metagpt
/metagpt_demo_agent --task "Write a game 2048"

🔧 Starting AIOS Demo with configuration:
  LLM: gpt-4o-mini (openai)
  Root Directory: root
  Memory Limit: 524288000 bytes
  Max Workers: 32
  Timeout: 300 seconds
  Agent: metagpt/metagpt_demo_agent
  Task: Write a game 2048
--------------------------------------------------
✅ Client initialized successfully
Status: {'llm': 'active', 'storage': 'active', 'memory': 'active', 'tool': 'active', 'scheduler': 'active'}
🚀 Executing agent: metagpt_demo_agent
📋 Task: Write a game 2048
✅ Agent execution completed

📊 Final Result:
{'agent_name': 'metagpt/metagpt_demo_agent', 'result': "ProjectRepo(/root/Cerebrum/metagpt/workspace/game_2048)\nDocs(['system_design/20241213121650.json', 'task/20241213121650.json', 'requirement.txt', 'prd/20241213121650.json'])\nSrcs(['game.py', 'static/script.js', 'static/style.css', 'templates/index.html', 'main.py'])", 'rounds': 1}
```





## Open-Interpreter

```shell
$ python example/aios_demo.py --llm_name gpt-4o-mini --llm_backend openai --aios_kernel_url http://127.0.0.1:8000 --agent open-interpreter/interpreter_demo_agent --task "In a group of 23 people, the probability of at least two having the same birthday is greater than 50%"

🔧 Starting AIOS Demo with configuration:
  LLM: gpt-4o-mini (openai)
  Root Directory: root
  Memory Limit: 524288000 bytes
  Max Workers: 32
  Timeout: 300 seconds
  Agent: open-interpreter/interpreter_demo_agent
  Task: In a group of 23 people, the probability of at least two having the same birthday is greater than 50%
--------------------------------------------------
✅ Client initialized successfully
Status: {'llm': 'active', 'storage': 'active', 'memory': 'active', 'tool': 'active', 'scheduler': 'active', 'factory': 'active'}
🚀 Executing agent: interpreter_demo_agent
📋 Task: In a group of 23 people, the probability of at least two having the same birthday is greater than 50%
✅ Agent execution completed

📊 Final Result:
{'agent_name': 'open-interpreter/interpreter_demo_agent', 'result': [{'role': 'assistant', 'type': 'code', 'format': 'python', 'content': 'import math\n\n# Calculate the probability that all 23 people have different birthdays\nnum_people = 23\nprob_all_unique = 1.0\n\nfor i in range(num_people):\n    prob_all_unique *= (365 - i) / 365\n\n# Calculate the probability of at least two sharing a birthday\nprob_at_least_one_shared = 1 - prob_all_unique\nprob_at_least_one_shared * 100  # Convert to percentage'}, {'role': 'computer', 'type': 'console', 'format': 'output', 'content': '50.729723432398565'}, {'role': 'assistant', 'type': 'message', 'content': 'In a group of 23 people, the probability of at least two people having the same birthday is approximately **50.73%**, which is indeed greater than 50%. This phenomenon is known as the "birthday paradox." If you have any other questions or need further explanation, feel free to ask!'}], 'rounds': 1}

```

**Review by dongyuanjushi — CHANGES_REQUESTED** [review]
Could you correct the utils/packge.py into utils/package.py and change the dependent files?

**Review by dongyuanjushi — APPROVED** [review]

**Pull request merged**
